pipeline {
    agent any
    
    tools {
        maven 'mvn-3.9.9'  // This name must match exactly from Global Tool Configuration
    }
    environment {
        IMAGE_NAME = "demo-app"
    }

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/Asaibaba/saibaba.git', branch: 'main'
            }
        }

        stage('Build') {
            steps {
                dir('sample-app') {
                sh 'mvn clean package -DskipTests=false'
                }
            }   
        }

        stage('Docker Build') {
            steps {
                dir('sample-app') {
                sh 'docker build -t $IMAGE_NAME .'
                }
            }
        }

        stage('Run Container') {
            steps {
                sh 'docker run -d -p 8081:8080 --name demo-container $IMAGE_NAME'
            }
        }
    }

    post {
        always {
            echo 'Cleaning up...'
            sh 'docker rm -f demo-1container || true'
        }
    }
}
