pipeline {
    agent any

    environment {
        IMAGE_NAME = "demo-app"
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/Asaibaba/saibaba.git'
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean package -DskipTests=false'
            }
        }

        stage('Docker Build') {
            steps {
                sh 'docker build -t $IMAGE_NAME .'
            }
        }

        stage('Run Container') {
            steps {
                sh 'docker run -d -p 8081:8080 --name demo-container $IMAGE_NAME'
            }
        }
    }

    post {
        always {
            echo 'Cleaning up...'
            sh 'docker rm -f demo-container || true'
        }
    }
}
